### ISSUE TITLE
License

### ISSUE THREAD

**Issue by siefkenj** [michael-brade/LaTeX.js#1]
Hi.  Would you mind specifying a license for LaTeX.js?  I would like to expand upon it.

**Comment by michael-brade** [comment]
Hey, that is so cool! My first issue, and a good one :) You are very welcome to expand it in any way, I just won't have enough time to work on it for a few more months. License is MIT, but I will add a file soon.

**Comment by michael-brade** [comment]
Done.

**Comment by siefkenj** [comment]
Thank you. This is great! 

If you're interested, I've just pushed code for my latex code beautifier: https://github.com/siefkenj/latex-parser
I ended up almost completely rewriting the PEG grammar. I don't know if it would be useful to you.

**Comment by michael-brade** [comment]
Nice idea! I didn't know you could use that grammar for pretty printing - but of course! :)

I hope you saw it - I changed and fixed *a lot* since your last message. Most important would probably be the beginning and the end of the grammar file, esp. the part about whitespaces. I think that is the core of the TeX/LaTeX grammar, the rest is just simply parsing macros (and environments)--a lot of code, but nothing fancy.
