### ISSUE TITLE
Error from PEG.js

### ISSUE THREAD

**Issue by johnwebner** [michael-brade/LaTeX.js#11]
When I tried to generate a parser with PEG.js and "LaTeX.js/src/latex-parser.pegjs" I got the following message:

**Line 228, column 5: Possible infinite loop when parsing (repetition used with an expression that may not consume any input).**

As you mentioned you parse TeX as a context-free grammar. Is it possible to share the context-free grammar or give some hints? I need a basic Latex parser in C#. Unfortunately after long reasearch I could not find any basic grammer or hint for an approach.

**Comment by williamstein** [comment]
For what it is worth, I've been using the following PEG.js grammar, which was maybe inspired by latex.js:

https://github.com/sagemathinc/cocalc/blob/react-latex/src/smc-webapp/latex-editor/peg/latex.pegjs

and definitely by https://github.com/siefkenj/latex-parser

Good luck!

**Comment by michael-brade** [comment]
@johnwebner yes, that is a limitation by PEG.js at the moment. It is not really an infinite loop, because I check with `&{}`. To overcome this, I added `plugin-pegjs.ls` to the build, see `package.json.sh` (and therefore `package.json`). The final command is: 

`pegjs -o dist/latex-parser.js --plugin ./dist/plugin-pegjs src/latex-parser.pegjs;`

That plugin removes the infinite loop check. Then it works.

@williamstein cool, so now we have already two projects continuing the latex.js grammar :) That's exciting! And makes me want to work on it even more (for it's not perfect yet).

**Comment by michael-brade** [comment]
I think the basic grammar would be in `src/latex-parser.pegjs`: the first 115 lines: https://github.com/michael-brade/LaTeX.js/blob/6b24bb1b601a1834be5fc3cc662ad22a8e08a558/src/latex-parser.pegjs#L1-L115

as well as the end, starting from line 733: https://github.com/michael-brade/LaTeX.js/blob/6b24bb1b601a1834be5fc3cc662ad22a8e08a558/src/latex-parser.pegjs#L733-L887

Of course, you will then have to implement functionality in C# that is equivalent to what `HtmlGenerator` does.

**Comment by michael-brade** [comment]
ANTLR4 is quite nice! Not a PEG parser, but quite generic. It can output *a lot* of different languages.

If you want something that is very similar to PEG.js, then take a look at [Pegasus](https://github.com/otac0n/Pegasus). It seems almost as if it copied the PEG.js syntax :)
