### ISSUE TITLE
LaTeX.js in C# + AST 

### ISSUE THREAD

**Issue by johnwebner** [michael-brade/LaTeX.js#13]
Hello,
I am trying to create a C# version of LaTeX.js in C# with AST as output. I am using [Pegasus](https://github.com/otac0n/Pegasus) as PEG parser generator.
Unfortunately I have some difficulties to understand _html-generator.js_ and _macros.js_ files, the **mode** of macros and the idea of **balancing**.

E.g. in my current version `\end{document}` is recognized as _hmode_macro_ instead of ending the document.

Could you please explain about balancing the groups and the [macros section](https://github.com/michael-brade/LaTeX.js/blob/6b24bb1b601a1834be5fc3cc662ad22a8e08a558/src/latex-parser.pegjs#L118-L213).

thanks

**Comment by michael-brade** [comment]
Good question! And Pegasus is a good choice!

Balancing the groups is quite easy. There are two separate things to do:

* Starting a new group on the grouping stack when encountering `{`. That copies the current attributes, labels, lengths, etc. into the new group, so that we can change those in the group while easily restoring the surrounding status when leaving the group by just popping the top group. The function for that is `HtmlGenerator.enterGroup`. It also increments the current balancing count. The function `HtmlGenerator.exitGroup` ends a group, pops it from the stack, and decrements the current balancing count.

* Keeping track of the nesting. Again, two different situations:
    - Simple groups in text may always be started with `{`, but they may only be ended iff at least one is currently open, i.e., the current status is unbalanced.
    - Macro arguments and environments need to contain balanced groups, so those may only be ended if the current status is balanced. Starting a new macro has to reset the balance count and start over, so each macro argument or environment starts a new (nested) level of balancing.

   To keep track of the balanced state, there is another stack (`_groups`) that contains the balancing count for the current level of groups. The functions for that are `HtmlGenerator.startBalanced` and `HtmlGenerator.endBalanced`. The parser calls `startBalanced` every time it encounters an argument, optional argument, and in the beginning at the start of the document.

**Comment by michael-brade** [comment]
The mode is what LaTeX also calls mode: there is a vertical mode, horizontal mode, and restricted horizontal mode. It is important to differentiate those because in restricted horizontal mode the browser may not break the text, and some macros may not be used in all of those modes.

That is why each macro has a "type", it can be V, H, or HV:
* V macros switch to vertical mode and only work in vertical mode
* H macros switch to horizontal mode and can only be used in horizontal mode
* HV macros can be used in all modes because such a macro doesn't output text. It just changes something, like `\bfseries` or `\setlength`. 

To implement this, I didn't explicitely keep track of the current mode. That would be too complicated and would probably also require another stack. Instead, it is built into the grammar itself. That is why there are three rules: `hv_macro`, `hmode_macro`, `vmode_macro`. Those rules only contain the macros that are allowed in that mode. And the three macros are themselves used only in those places where they are allowed.

And last, the rules `is_*` check the current macro for its type. So I can create a rule like `&is_preamble only_preamble`, which first checks if the current macro is a preamble macro (not eating any input), and if so, executes the rule `only_preamble`. `only_preamble` then throws an error and says that this macro may only be used in the preamble.

Hope this helps! If anything remains unclear, just let me know.

**Comment by johnwebner** [comment]
Thank your reply.
After implementing the group and balance stuff the program worked fine.
I have used [livescript compiler](http://livescript.net/) to tranlate your program into JS.
First I have some question about the mode.
I have recognized that you used arrays for some macros to determine their mode and the arguments.
But you did not do that for all the macros the same way and for some macros (e.g. `\section`) you did not define such an array at all.
Is there a reason for that?
How do you determine the arguments for a macro you did not define an array for?
Does [this](https://github.com/michael-brade/LaTeX.js/blob/f2339cf73f5aee4d708a0e0d494428c8bb7f855d/src/html-generator.ls#L525) mean e.g. `\section` is a H mode macro?
I would like to support basic `\newcommand` but handling that is different as I read some papers. Do you think it is possible to implement `\newcommand` in peg?

**Comment by johnwebner** [comment]
Thank you for your reply.
After implementing the group and balance stuff the program worked fine.
I have used [livescript compiler](http://livescript.net/) to tranlate your program into JS.
First I have some question about the mode.
I have recognized that you used arrays for some macros to determine their mode and the arguments.
But you did not do that for all the macros the same way and for some macros (e.g. \section) you did not define such an array at all.
Is there a reason for that?
How do you determine the arguments for a macro you did not define an array for?
Does [this ](https://github.com/michael-brade/LaTeX.js/blob/f2339cf73f5aee4d708a0e0d494428c8bb7f855d/src/html-generator.ls#L525)mean e.g. `\section` is a H mode macro?
I would like to support basic `\newcommand` but handling that is different as I read some papers. Do you think it is possible to implement `\newcommand` in peg?

**Comment by michael-brade** [comment]
Great, that is good news! To answer your questions:

- yes, line 525 means exactly that: most macros without any arguments are constants and thus horizontal mode macros, so it's easier to allow defining them without the need for an argument descriptor, hence the default 

- however, it is not true for `\section`. Look [here](https://github.com/michael-brade/LaTeX.js/blob/f2339cf73f5aee4d708a0e0d494428c8bb7f855d/src/documentclasses/base.ls#L84-L90) :)

**Comment by michael-brade** [comment]
I actually started to implement `\newcommand`, here is what I have so far:

    # custom macro definition

    # \(re)newcommand*{\cmd}[nargs][optargdefault]{defn}
    args
     ..\newcommand =    \
     ..\renewcommand =  <[ HV s m n? o? g ]>

    \newcommand         : (s, macro, n, argdefault, data) !->

    \renewcommand       : (s, macro, n, argdefault, data) !->

But I ran into some trouble (that I don't remember at the moment), that's why I stopped. I think it was because `data` has to be an AST, otherwise the code would be interpreted too soon. And I don't have an AST yet :( With an AST, I am sure you can implement the essential functionality of `\newcommand` in PEG.

**Comment by johnwebner** [comment]
Your LaTeX grammar is the most advanced grammar I could find.
Did you create it from your own LaTeX knowledge or do you know a source to recommend?

In LaTeX.js a `\section` must have an `arg_group` as an argument.
`arg_group` is defined as `paragraph_with_linebreak*` and a `paragraph_with_linebreak` can be a `vmode_macro` e.g. a `\section`. That means LaTeX.js accepts `\section{\section{Characters}}` something LaTeX does not accept.

**Comment by johnwebner** [comment]
Your LaTeX grammar is the most advanced grammar I could find.
Is the grammar based on your own LaTeX knowledge or do you know a source to recommend?

In LaTeX.js a `\section` must have an `arg_group` as an argument.
`arg_group` is defined as `paragraph_with_linebreak*` and a `paragraph_with_linebreak` can be a `vmode_macro` e.g. a `\section`. That means LaTeX.js accepts `\section{\section{Characters}}` something LaTeX does not accept.

**Comment by michael-brade** [comment]
Yes, I wrote the grammar all by myself with just the knowledge I had about LaTeX. One day I thought, "Gee, this should be easy, only text and a few sections! Why has no one else done it yet?" So I started by writing a grammar for just paragraphs of text. I did not expect that already the whitespace handling would be that complicated to get right! And now, almost three years later, I am still not done...

And yes, LaTeX.js can do some things LaTeX cannot. Usually I did than when it would have been more work to prevent something than to just allow it, like using `\verb` anywhere, which is not possible in LaTeX. But it makes sense, so why forbid it?

However, I do know that `arg_group` is wrong. In fact, `paragraph_with_linebreak` shouldn't exist at all, it was a mistake. But since it didn't really hurt, I haven't spent the time to fix it yet. It is on my TODO list :)
