### ISSUE TITLE
Migration to rollup

### ISSUE THREAD

**Issue by fgborges** [michael-brade/LaTeX.js#69]
Now we can migrate to rollup! but other library prevent to execute tests, thus let's start to do them if the issue solved. https://github.com/foliojs/unicode-properties/issues/9

**Comment by michael-brade** [comment]
hm... I don't think I understood the part that prevents execution of tests. What problem is it?

**Comment by fgborges** [comment]
A the time, that package **was** a problem, some dependencies depends that package. that package lacked some js files but updated. Now we have other problems. I tackle those of problems.

**Comment by michael-brade** [comment]
Ok, fair enough :smile:

**Comment by fgborges** [comment]
We ready to migrate! Please try it first locally and merge  `rollup` branch to your master branch if you have no problem. 👍

**Comment by michael-brade** [comment]
No worries, take your time! The code looks really nice so far!

**Comment by fgborges** [comment]
@michael-brade Could you check my branch ? For me, It seems that there is no problem.

- [x] Support dynamic import (you don't neet to add no more line!)
- [x] Remove webpack
- [x] Build playground with rollup

**Comment by michael-brade** [comment]
Wow, *very* well done indeed! Actually, I'm surprised how much better it is :grin: 

I saw that you removed the `devbuild` script - might be fine actually, since we have sourcemaps. But when I'm impatient I want to have the build as fast as possible :-) Maybe I'll add it again. And I like this:
https://github.com/rollup/rollup/pull/1389#issuecomment-306023246, that might speed it up as well.

However, I'll be offline for 12 days from tomorrow on (probably) but I'll have enough time to merge this tomorrow. You could also create a pull request if you want to :-)

**Comment by michael-brade** [comment]
Oh, and I noticed that the playground code is old--I didn't commit the current status yet, therefore the code breaks. Sorry about that. I guess it is time to do a new release soon. But first, I want to fix the bug you found regaring starred environments.
