### ISSUE TITLE
Unable to load package

### ISSUE THREAD

**Issue by Wanderish** [michael-brade/LaTeX.js#76]
Hey @michael-brade, I'm pretty new to Latex (like really new).
I'm trying to embed some latex into an html page but I've hit a block trying to display the equations and images because of these errors:

- error loading package "amsmath": ReferenceError: require is not defined

- Uncaught (in promise) peg$SyntaxError {message: "unknown environment: equation", expected: null, found: null, location: {…}, name: "SyntaxError", …}

There is a folder named "package" containing files with extension .ls
Did a couple of searches as well regarding that issue but all in vain.
Any suggestions or directions would be great, man.
Thanks in advance.

Update: Here's a codepen link to what I've been trying and what I'm stuck with
https://codepen.io/wanderish/pen/MMqegj

**Comment by michael-brade** [comment]
Hi Shreyas, 
thanks for the example, that helps a lot :-) Yes, those error messages could obviously be improved, but it works as intended: I did not implement an `amsmath` package yet, hence the "error loading package". Too bad it says "require is not defined", that was introduced with the switch to rollup and needs fixing.

I also didn't implement the `equation` environment yet, so that is why it says "unknown environment". But you could switch to math mode using `$$` and then use an environment that KaTeX supports, like this:
```
$$\begin{aligned} 
I_\theta = I_0\cos^2\theta
\end{aligned}$$
```
I will implement math environments eventually, hopefully soon...

The .ls files are LiveScript source files. They are compiled to JavaScript.

**Comment by Wanderish** [comment]
Thanks for the suggestion about the `$$` . That really helped.
Um, how do I make use of those LiveScript source files?

**Comment by michael-brade** [comment]
You don't :stuck_out_tongue_winking_eye: They are already compiled into the bundle.

**Comment by Wanderish** [comment]
But I'm unable to render any graphic latex code into the html page. It gives the same error as it was giving to the `amsmath` package :\ :|

**Comment by michael-brade** [comment]
oh.. can you give me an example again? Maybe you tried to load an unsupported package?

**Comment by Wanderish** [comment]
Hey, sorry about the late reply. Was busy with work.

About the issue: My senior faculties decided that it was taking too long to complete the task and proposed a non-latex way solution. So for now I'm not using latex in the feature.
But I'm pretty sure we'll be coming back to it in some while. I might need your assistance then. 
I'll post an example pen with the error in a few days. 
Thanks for your help! 
Cheers :)
