### ISSUE TITLE
Does it only support article template?

### ISSUE THREAD

**Issue by lanfeiying** [michael-brade/LaTeX.js#96]
Hi,
I am currently using LaTeX.js to convert LaTeX document to HTML. I have a question about the LaTeX template it can support. I have tested IEEEtran template but failed to generate HTML.
Does it support other template? Or can I modify the format?
By the way, does it support a bibliograph? I need to add references so that I am wondering if it supports generating a reference list.
Thanks for your work!

**Comment by michael-brade** [comment]
Hi, yeah, currently, I have only implemented article, book, report. You could implement it yourself by adding a new (javascript) class to `src/documentclasses`. And no, I haven't done any work on `\cite` yet... and it will take quite a while until I get there because first I want to finish the basic things like table and figures and fix the remaining whitespace bugs. And create an AST. All while I have very little time until April or so.
